export const Movies = [
    {
        id: 1,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 2,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 3,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 4,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 5,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 6,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 7,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
    {
        id: 8,
        title: 'Pulp Fiction',
        releaseDate: 2004,
        genre: 'Action & Adventure',
        url: 'https://www.miramax.com/media/assets/Pulp-Fiction1.png',
    },
];
